### ISSUE TITLE
Some elements need to be more descriptive

### ISSUE THREAD

**Issue by zamcham** [J-C-S-V/Portfolio-setup-and-mobile-first#10]
It was a good show, but you still need to improve a bit to proceed further. We found the following short-comings in the project and would suggest you to make the following changes.

```
<li class="skills-boxed">
                <img src="./img/JS.png" alt="Javascript" />JavaScript
              </li>
              <li class="skills-boxed">
                <img src="./img/HTML.png" alt="HTML" />HTML
              </li>
              <li class="skills-boxed">
                <img src="./img/CSS3.png" alt="CSS3" />CSS
              </li>
            </ul>       
```                                                                                                                     
- We think it's maybe better to have a more descriptive alt text like CSS-icon
- Down arrow was not used with the language. Please amend that arrow currently its a `v`
- Languages `html`,`css` and `JS` are not aligned left as per figma design 
- In the contact form, the submit button is not good. On `hover` it becomes invisible.

**Comment by J-C-S-V** [comment]
Thank you for the feedback!
