### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by danielamoreno699** [J-C-S-V/Portfolio-setup-and-mobile-first#12]
- I suggest to rename the main files for css and js. (eg : styles.css, main.js)
- For simplicity and in order to reduce lines of code, I suggest you to use InnerHtml instead of createElement.
- I suggest you to remove the created html element in the closing event.
@edy : Suggests to remove inline comments of the code.

**Comment by J-C-S-V** [comment]
Thank you for the feedback!
